"""initial

Revision ID: 0001
Revises:
Create Date: 2026-05-13 09:34:54.358270

"""
from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('map_seed', sa.Integer(), nullable=False),
    sa.Column('map_preset', sa.String(length=64), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('phase_deadline_hours', sa.Integer(), nullable=True),
    sa.Column('current_phase_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discord_webhook_url', sa.Text(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_status_deadline', ['status', 'current_phase_deadline_at'], unique=False)

    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('sender_idx', sa.Integer(), nullable=False),
    sa.Column('recipients_mask', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_seats',
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('player_idx', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bot_class', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_idx')
    )
    with op.batch_alter_table('game_seats', schema=None) as batch_op:
        batch_op.create_index('ix_game_seats_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_seats', schema=None) as batch_op:
        batch_op.drop_index('ix_game_seats_user')

    op.drop_table('game_seats')
    op.drop_table('chat_messages')
    op.drop_table('sessions')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_status_deadline')

    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
